/*
Project Euler Problem 12:

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include <iostream>
#include <cmath>

using namespace std;


int main(int argc, char const *argv[]) {
    int t = 0, pf;

    for (int n = 1; true; n++) {
        t += n;
        pf = 0;
        for (int x = 2; x <= ceil(sqrt(t)); x++) {
            if (t % x == 0) {
                pf+=2;
            }
        }
        if (pf > 500) {
            cout << t << endl;
            return 0;
        }
    }
}
